bot:
  backup_time: '0'
  search:
    per_page: 5
    z_url: true
user:
  admin: 410690676 # 管理员用户id，可通过 https://t.me/getletbot 获取id
  member: []  # 允许使用bot的 用户、群组、频道（群组和频道id需要加上-100）可通过 https://t.me/getletbot 获取id。 留空为所有人可用
  alist_host: http://178.128.26.138:5244 # alist ip:port或alist域名，一般填域名即可
  alist_web: "https://alist.cloudservertech.my.id" # 你的alist域名
  alist_token: "alist-04a33a57-64bf-4199-a7af-25adfdbb9b77ijv4JYDuv2yd3NYkXSiErP2tDVHKxsPkFFEAYP8B4gRh5AJNiwbl90fZxf3eI0b6" # alist token
  bot_token: "6353455060:AAEpBLuHGCQupNTjiNSvs9o51l0ky3B9Xao" # bot的api token，从 @BotFather 获取
  api_id: "28597492" # api_id、api_hash在 https://my.telegram.org/apps 获取
  api_hash: "d181e8921dbe3033dbf8b25074c64cdd"
proxy:
  scheme:  # 支持“socks4”、“socks5”和“http”，不填则不使用代理，例：http
  hostname: #例：127.0.0.1
  port: #例：7890
